ALL: ex5opt_ic

PETSC_DIR       =/projects/ATPESC2018/FASTMath/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/petsc-develop-xufshydc44bard4v7qinrl2nfetl7fcm
CLFAGS          =
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          =
EXAMPLESC       =
EXAMPLESF       =
EXAMPLESFH      =
MANSEC          = TS
DIRS            =
CLEANFILES      = SA-data/* ex5opt_ic

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
